name: "Bug Report"
description: "Report a bug"
labels: ["status/awaiting_triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## BEFORE POSTING YOUR ISSUE
        - Please create GitHub issues only for Yoast bugs. GitHub issues ARE NOT FOR SUPPORT.
        - Make sure you are using the most updated versions of Yoast, WordPress & your theme.
        ## THE ISSUE
  - type: checkboxes
    id: prerequisites
    attributes:
      label: "Prerequisites"
      options:
        - label: "I've read and understood the [contribution guidelines](https://github.com/Yoast/wordpress-seo/blob/trunk/.github/CONTRIBUTING.md)"
          required: true
        - label: "I've searched for any related issues and avoided creating a duplicate issue."
          required: true
